# Generated by Django 6.1 on 2026-08-17 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('seat_limit', models.PositiveIntegerField(blank=True, help_text='null = unlimited', null=True)),
                ('project_limit', models.PositiveIntegerField(blank=True, help_text='null = unlimited', null=True)),
                ('monthly_price_ngn', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'billing_plan',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('opay', 'Opay')], max_length=20)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_webhook_event',
                'indexes': [models.Index(fields=['provider', 'event_type'], name='billing_web_provide_c20642_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='uniq_webhook_provider_event')],
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('opay', 'Opay')], max_length=20)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=128)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_entitlement',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('organization',), name='uniq_active_entitlement_per_org')],
            },
        ),
    ]
