# Generated by Django 6.1 on 2026-08-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='provider',
            field=models.CharField(choices=[('none', 'None (Trial / Manual)'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='provider',
            field=models.CharField(choices=[('none', 'None (Trial / Manual)'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=20),
        ),
    ]
