# Generated by Django 6.1 on 2026-08-17 21:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_seed_extended_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('invoice_overdue', 'Invoice Overdue'), ('invoice_paid', 'Invoice Paid'), ('lead_assigned', 'Lead Assigned'), ('lead_converted', 'Lead Converted'), ('task_assigned', 'Task Assigned'), ('task_due_soon', 'Task Due Soon'), ('project_status_changed', 'Project Status Changed'), ('member_invited', 'Member Invited'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'recipient', 'is_read'], name='notificatio_organiz_5cc15d_idx'), models.Index(fields=['organization', 'recipient', 'created_at'], name='notificatio_organiz_e0fe59_idx')],
            },
        ),
    ]
