# Generated by Django 6.1 on 2026-08-17 21:35

import apps.documents.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_seed_extended_permissions'),
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'csv', 'txt', 'zip'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=127)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
                'indexes': [models.Index(fields=['organization', 'customer'], name='documents_d_organiz_08aa22_idx'), models.Index(fields=['organization', 'project'], name='documents_d_organiz_fe9de9_idx'), models.Index(fields=['organization', 'invoice'], name='documents_d_organiz_89bc10_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('invoice__isnull', True), ('project__isnull', True)), models.Q(('customer__isnull', True), ('invoice__isnull', True), ('project__isnull', False)), models.Q(('customer__isnull', True), ('invoice__isnull', False), ('project__isnull', True)), _connector='OR'), name='document_exactly_one_owner'), models.CheckConstraint(condition=models.Q(('size_bytes__lte', 26214400)), name='document_max_size')],
            },
        ),
    ]
