# Generated by Django 6.1 on 2026-08-17 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('primary_contact_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('billing_address', models.TextField(blank=True)),
                ('data_source', models.CharField(choices=[('direct', 'Collected directly from the customer'), ('lead_conversion', 'Converted from a Lead'), ('imported', 'Imported/purchased list'), ('referral', 'Referral')], default='direct', max_length=30)),
                ('consent_obtained_at', models.DateTimeField(blank=True, help_text='Required when data_source is not DIRECT — records when lawful-basis consent was obtained for third-party-sourced data.', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Ordinary workflow archive/hide. NOT an NDPA erasure mechanism — use hard_delete() for data-subject deletion requests.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
            ],
            options={
                'db_table': 'customers_customer',
                'indexes': [models.Index(fields=['organization', 'is_archived'], name='customers_c_organiz_fe428c_idx')],
            },
        ),
    ]
