# Generated by Django 6.1 on 2026-08-17 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('data_source', models.CharField(choices=[('direct', 'Collected directly'), ('imported', 'Imported/purchased list'), ('referral', 'Referral'), ('inbound', 'Inbound (website/marketing)')], default='direct', max_length=20)),
                ('consent_obtained_at', models.DateTimeField(blank=True, help_text='Required when data_source is not DIRECT (NDPA consent tracking).', null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_leads', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
            ],
            options={
                'db_table': 'leads_lead',
                'indexes': [models.Index(fields=['organization', 'status'], name='leads_lead_organiz_1ed3c6_idx')],
            },
        ),
    ]
